object_type_threshold: 0.12
object_parts_threshold: 0.03
top_height_threshold: 0.07
flat_top_min_points_threshold: 0.8
downsampling_step: 0.005
minimum_handle_points: 35
circle_minimum_radius: 0.2
inliers_circle_threshold: 0.7
circle_ransac_distance_threshold: 0.005
handle_distance_threshold: 0.002
vertical_height_threshold: 0.05
centroid_distance_threshold: 0.005
processing_frame: /table
world_frame_id: /base_link
camera_frame_id: /openni_rgb_optical_frame
