object_type_threshold: 0.1
object_parts_threshold: 0.03
top_height_threshold: 0.07
flat_top_min_points_threshold: 0.8
downsampling_step: 0.003
minimum_handle_points: 150
circle_threshold: 0.83
processing_frame: /table
world_frame_id: /base_link
camera_frame_id: /openni_rgb_optical_frame
